n = input("Digite algo: ")
print("Só tem espaço? {}", n.isspace())
print("É um número? {}", n.isnumeric())
print("É alfabético? {}", n.isalpha())
print("É alfanumerico? {}", n.isalnum())
print("Está em maiuscula? {}", n.isupper())
print("Está em minuscula? {}", n.islower())
print("Está capitalizada {}", n.istitle())
