n = int(input("Digite o número que deseja mostrar a tabuada: "))
print("{} * 1 = {}".format(n, n*1), end="")
print("{:>10} * 2 = {}".format(n, n*2), end="")
print("{:>10} * 3 = {}".format(n, n*3))
print("{} * 4 = {}".format(n, n*4), end="")
print("{:>10} * 5 = {}".format(n, n*5), end="")
print("{:>10} * 6 = {}".format(n, n*6))
print("{} * 7 = {}".format(n, n*7), end="")
print("{:>10} * 8 = {}".format(n, n*8), end="")
print("{:>10} * 9 = {}".format(n, n*9))
